# EREBUS — Primordial Darkness
# Omarchy Alacritty

[window]
padding = { x = 10, y = 8 }
opacity = 0.96

[font]
normal = { family = "JetBrains Mono" }
size = 11.0

[colors.primary]
background = "#08090A"
foreground = "#D6D3CE"

[colors.cursor]
text = "#08090A"
cursor = "#B52A32"

[colors.selection]
text = "#FFFFFF"
background = "#8B1E24"

[colors.normal]
black = "#08090A"
red = "#8B1E24"
green = "#66705C"
yellow = "#9A8052"
blue = "#8B1E24"
magenta = "#62505A"
cyan = "#526868"
white = "#D6D3CE"

[colors.bright]
black = "#77746F"
red = "#B52A32"
green = "#849477"
yellow = "#C4A66B"
blue = "#B52A32"
magenta = "#8A6F7D"
cyan = "#759292"
white = "#FFFFFF"
