# EREBUS — Primordial Darkness
# Omarchy 4.x theme

general {
    col.active_border = 0xff8b1e24
    col.inactive_border = 0xff292b2e
}

group {
    col.border_active = 0xff8b1e24
    col.border_inactive = 0xff292b2e
    col.border_locked_active = 0xffb52a32
    col.border_locked_inactive = 0xff292b2e

    groupbar {
        col.active = 0xff8b1e24
        col.inactive = 0xff181a1d
        text_color = 0xffd6d3ce
    }
}

misc {
    background_color = 0xff08090a
}
