# EREBUS — Primordial Darkness
# Omarchy Kitty

background #08090A
foreground #D6D3CE

selection_background #8B1E24
selection_foreground #FFFFFF

cursor #B52A32
cursor_text_color #08090A

url_color #B52A32

active_border_color #8B1E24
inactive_border_color #292B2E

# Black
color0 #08090A
color8 #77746F

# Red
color1 #8B1E24
color9 #B52A32

# Green
color2 #66705C
color10 #849477

# Yellow
color3 #9A8052
color11 #C4A66B

# Blue
color4 #4E5966
color12 #718091

# Magenta
color5 #62505A
color13 #8A6F7D

# Cyan
color6 #526868
color14 #759292

# White
color7 #D6D3CE
color15 #FFFFFF

font_family JetBrains Mono
font_size 11.0

window_padding_width 10
window_padding_height 8

confirm_os_window_close 0
enable_audio_bell no
