# EREBUS — Primordial Darkness
# Omarchy Alacritty

[window]
padding = { x = 10, y = 8 }
opacity = 0.96

[font]
normal = { family = "JetBrains Mono" }
size = 11.0

[colors.primary]
background = "#050505"
foreground = "#B8B5B0"

[colors.cursor]
text = "#050505"
cursor = "#A82430"

[colors.selection]
text = "#FFFFFF"
background = "#5A1820"

[colors.normal]
black = "#050505"
red = "#5A1820"
green = "#4F5A4B"
yellow = "#75613F"
blue = "#5A1820"
magenta = "#463943"
cyan = "#3F5151"
white = "#B8B5B0"

[colors.bright]
black = "#5F5D59"
red = "#A82430"
green = "#849477"
yellow = "#C4A66B"
blue = "#A82430"
magenta = "#8A6F7D"
cyan = "#759292"
white = "#FFFFFF"
