# EREBUS — DAWN

general {
    col.active_border = 0xff6b252b
    col.inactive_border = 0xff111111
}

group {
    col.border_active = 0xff6b252b
    col.border_inactive = 0xff111111
}

misc {
    background_color = 0xff0d0d0d
}
