# EREBUS — Primordial Darkness

theme[main_bg]="#08090A"
theme[main_fg]="#D6D3CE"

theme[title]="#B52A32"
theme[hi_fg]="#FFFFFF"
theme[selected_bg]="#8B1E24"
theme[selected_fg]="#FFFFFF"

theme[inactive_fg]="#77746F"

theme[graph_text]="#D6D3CE"
theme[meter_bg]="#181A1D"
theme[proc_misc]="#77746F"

theme[cpu_box]="#292B2E"
theme[mem_box]="#292B2E"
theme[net_box]="#292B2E"
theme[proc_box]="#292B2E"

theme[div_line]="#292B2E"
theme[temp_start]="#8B1E24"
theme[temp_mid]="#B52A32"
theme[temp_end]="#D6D3CE"

theme[cpu_start]="#8B1E24"
theme[cpu_mid]="#B52A32"
theme[cpu_end]="#D6D3CE"

theme[free_start]="#66705C"
theme[free_mid]="#849477"
theme[free_end]="#D6D3CE"

theme[cached_start]="#62505A"
theme[cached_mid]="#8A6F7D"
theme[cached_end]="#D6D3CE"

theme[available_start]="#4E5966"
theme[available_mid]="#718091"
theme[available_end]="#D6D3CE"

theme[used_start]="#8B1E24"
theme[used_mid]="#B52A32"
theme[used_end]="#D6D3CE"

theme[download_start]="#8B1E24"
theme[download_mid]="#B52A32"
theme[download_end]="#D6D3CE"

theme[upload_start]="#62505A"
theme[upload_mid]="#8A6F7D"
theme[upload_end]="#D6D3CE"

theme[process_start]="#8B1E24"
theme[process_mid]="#B52A32"
theme[process_end]="#D6D3CE"
