# EREBUS — NIGHT

general {
    col.active_border = 0xff4d141b
    col.inactive_border = 0xff111111
}

group {
    col.border_active = 0xff4d141b
    col.border_inactive = 0xff111111
}

misc {
    background_color = 0xff030303
}
