# EREBUS — Primordial Darkness
# Omarchy Mako

background-color=#111315
text-color=#D6D3CE
border-color=#8B1E24

border-size=2
border-radius=3

padding=10
margin=10

font=JetBrains Mono 11

default-timeout=5000

[urgency=low]
border-color=#292B2E
text-color=#77746F

[urgency=normal]
border-color=#8B1E24
text-color=#D6D3CE

[urgency=high]
border-color=#B52A32
text-color=#FFFFFF
background-color=#181A1D
