# EREBUS — DUSK

general {
    col.active_border = 0xff651820
    col.inactive_border = 0xff111111
}

group {
    col.border_active = 0xff651820
    col.border_inactive = 0xff111111
}

misc {
    background_color = 0xff050505
}
